apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP # Prístupné iba zvnútra klastra (bezpečné)
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
