apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Tento súbor definuje zoznam spoločných základných súborov.
# Žiadny z nich nemá napevno priradený namespace, aby sme ich mohli opätovne použiť.
resources:
  - postgres-pvc.yaml
  - postgres-service.yaml
  - postgres-deployment.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
