# Configuration for Frontend Service
service: docker-task-frontend
image: adoosdeveloper/docker-task-frontend

servers:
  web:
    proxy:
  host: 164.92.244.115
  app_port: 80
traefik:
  host_port: 8080

registry:
  username: adoosdeveloper
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  context: ./frontend
  dockerfile: ./frontend/Dockerfile
  args:
    VITE_API_URL: http://164.92.244.115:3000
